name: CI build for docker action
on:
  push:
    branches: [main]
    paths: [HiTeam]
  workflow_dispatch:

jobs:
  container-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3.3.0

      - name: run my action
        uses: ./HiTeam
        with:
          who-to-greet: "you"
