name: docker action demo
on:
  push:
    branches: [main,housten-dryrun]
    paths: [HiTeam/**]
  workflow_dispatch:
    inputs:
      victim:
        default: "you"
      

jobs:
  container-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.3.0

      - name: run my action
        id: run-action
        uses: ./HiTeam
        with:
          who-to-greet: "${{ github.event.inputs.victim }} "

      - name: Print Output
        id: output
        run: echo "${{ steps.run-action.outputs.greeting }}"
